export const PRODS = [
  {
    id: 1,
    name: "Dynamic Mist",
    sub: "Pour Homme",
    cat: "Fresh & Aquatic",
    price: 2800,
    cls: "bg-linear-to-br from-[#0c1828] to-[#0f2035]",
    image: "/products/dynamicmist.jpeg",
    notes: ["Fresh", "Aquatic", "Woody"],
    desc: "A burst of ocean breeze and citrus with a warm musky base.",
  },
  {
    id: 2,
    name: "Tempest Noir",
    sub: "Pour Homme",
    cat: "Dark & Intense",
    price: 3200,
    cls: "bg-linear-to-br from-[#060606] to-[#111111]",
    image: "/products/tempestnoir.jpeg",
    notes: ["Dark", "Spicy", "Bold"],
    desc: "Stormy, dramatic, irresistibly intense. Black pepper and vetiver.",
  },
  {
    id: 3,
    name: "Executive Code",
    sub: "Pour Homme",
    cat: "Sophisticated",
    price: 3000,
    cls: "bg-linear-to-br from-[#0a0a0a] to-[#181818]",
    image: "/products/executivecode.jpeg",
    notes: ["Woody", "Elegant", "Clean"],
    desc: "Boardroom-ready elegance. Sandalwood and amber in perfect harmony.",
  },
  {
    id: 4,
    name: "Oud Royale",
    sub: "Pour Homme",
    cat: "Oriental & Luxe",
    price: 3500,
    cls: "bg-linear-to-br from-[#0e0c06] to-[#1a1508]",
    image: "/products/oudroyale.jpeg",
    notes: ["Oud", "Resin", "Royal"],
    desc: "The king of orientals. Deep oud, sacred saffron and rose.",
  },
  {
    id: 5,
    name: "Velvet Éclat",
    sub: "Pour Femme",
    cat: "Floral & Feminine",
    price: 3000,
    cls: "bg-linear-to-br from-[#200a18] to-[#321228]",
    image: "/products/velveteclat.jpeg",
    notes: ["Rose", "Floral", "Soft"],
    desc: "Radiant roses draped in velvet musk. Pure femininity.",
  },
  {
    id: 6,
    name: "Citrus Elixir",
    sub: "Pour Homme",
    cat: "Fresh & Vibrant",
    price: 2800,
    cls: "bg-linear-to-br from-[#081208] to-[#0c1a0a]",
    image: "/products/citruselixir.jpeg",
    notes: ["Citrus", "Green", "Energizing"],
    desc: "Zesty bergamot, lime and neroli — the ultimate daytime freshness.",
  },
];

export const CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Bahawalpur",
  "Sargodha",
  "Sukkur",
];

export const SHEET_URL =
  "https://script.google.com/macros/s/AKfycbzJ-e6FbB2zm2FMgSjBQ3lUu19z0hn1MmtlilHSrzUP2kuuKLVN1_s0B2g5n6fO1EEVrA/exec";
